version: "3.8"

services:

  postgres:
    image: docker.io/library/postgres:16
    environment:
      POSTGRES_USER: guac
      POSTGRES_PASSWORD: guac
    expose:
      - 5432
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data:z
    healthcheck:
      test: ["CMD", "pg_isready", "--username=guac", "--dbname=guac"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
  postgrest:
    container_name: postgrest
    image: postgrest/postgrest:latest
    ports:
      - "3000:3000"
    # Available environment variables documented here:
    # https://postgrest.org/en/latest/configuration.html#environment-variables
    environment:
      # The standard connection URI format, documented at
      # https://www.postgresql.org/docs/current/static/libpq-connect.html#LIBPQ-CONNSTRING
      - PGRST_DB_URI=postgres://guac:guac@postgres:5432/guac
      # The name of which database schema to expose to REST clients
      - PGRST_DB_SCHEMA=public
      # The database role to use when no client authentication is provided
      - PGRST_DB_ANON_ROLE=guac
      # Overrides the base URL used within the OpenAPI self-documentation hosted at the API root path
      - PGRST_OPENAPI_SERVER_PROXY_URI=http://localhost:3000
    # networks:
    #   - postgrest-backend
    restart: on-failure
    depends_on:
      postgres:
        condition: service_healthy

  graphql:
    image: $GUAC_IMAGE
    command: "/opt/guac/guacgql --gql-debug --gql-backend=ent --db-address=postgres://guac:guac@postgres:5432/guac?sslmode=disable"
    working_dir: /guac
    restart: on-failure
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:8080"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 5s

  nats:
    image: "docker.io/library/nats:2.9.17-alpine"
    command: "--jetstream -m 8222"
    ports:
      - "4222:4222"
      # monitoring port
      - "8222:8222"
    restart: on-failure
    healthcheck:
      test: [ "CMD", "wget", "--spider", "http://localhost:8222/healthz" ]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 5s

  ingestor:
    image: $GUAC_IMAGE
    command: "/opt/guac/guacingest --blob-addr=file:///tmp/blobstore?no_tmp_dir=true --csub-addr=collectsub:2782 --gql-addr=http://graphql:8080/query --pubsub-addr=nats://nats:4222"
    working_dir: /guac
    restart: on-failure
    depends_on:
      collectsub:
        condition: service_healthy
      graphql:
        condition: service_healthy
      nats:
        condition: service_healthy
    volumes:
      - /tmp/blobstore:/tmp/blobstore:z


  collectsub:
    image: $GUAC_IMAGE
    command: "/opt/guac/guaccsub"
    working_dir: /guac
    restart: on-failure
    ports:
      - "2782:2782"
    healthcheck:
      test: [ "CMD", "wget", "--spider", "http://localhost:2782" ]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 5s

  depsdev-collector:
    image: $GUAC_IMAGE
    command: "/opt/guac/guaccollect deps_dev --csub-addr=collectsub:2782 --blob-addr=file:///tmp/blobstore?no_tmp_dir=true  --pubsub-addr=nats://nats:4222"
    working_dir: /guac
    restart: on-failure
    environment:
      - DEPS_DEV_APIKEY
    depends_on:
      collectsub:
        condition: service_healthy
      nats:
        condition: service_healthy
    volumes:
      - ./blobstore:/tmp/blobstore:z

  cd-certifier:
    image: $GUAC_IMAGE
    command: "/opt/guac/guacone certifier cd -p --csub-addr=collectsub:2782 --gql-addr=http://graphql:8080/query"
    working_dir: /guac
    restart: on-failure
    depends_on:
      collectsub:
        condition: service_healthy
      nats:
        condition: service_healthy
    volumes:
      - ./blobstore:/tmp/blobstore:z

  oci-collector:
    image: $GUAC_IMAGE
    command: "/opt/guac/guaccollect image --csub-addr=collectsub:2782 --blob-addr=file:///tmp/blobstore?no_tmp_dir=true  --pubsub-addr=nats://nats:4222"
    working_dir: /guac
    restart: on-failure
    depends_on:
      collectsub:
        condition: service_healthy
      nats:
        condition: service_healthy
    volumes:
      - ./blobstore:/tmp/blobstore:z

  osv-certifier:
    image: $GUAC_IMAGE
    command: "/opt/guac/guacone certifier osv -p --csub-addr=collectsub:2782 --gql-addr=http://graphql:8080/query"
    working_dir: /guac
    restart: on-failure
    depends_on:
      collectsub:
        condition: service_healthy
      graphql:
        condition: service_healthy

  guac-rest:
    image: $GUAC_IMAGE
    command: "/opt/guac/guacrest --rest-api-server-port=8081 --gql-addr=http://graphql:8080/query"
    working_dir: /guac
    restart: on-failure
    ports:
      - "8081:8081"
    depends_on:
      graphql:
        condition: service_healthy
